# Generated by Django 4.2.7 on 2025-11-01 18:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meter_id', models.CharField(default='APARTMENT_METER', help_text='Unique identifier for the electricity meter', max_length=100)),
                ('timestamp', models.DateTimeField(help_text='Date and time of the measurement')),
                ('consumption_kwh', models.DecimalField(decimal_places=3, help_text='Electricity consumption in kilowatt-hours', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('cost', models.DecimalField(blank=True, decimal_places=2, help_text='Cost of consumption in dollars', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('voltage', models.DecimalField(blank=True, decimal_places=2, help_text='Voltage reading in volts', max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('current', models.DecimalField(blank=True, decimal_places=2, help_text='Current reading in amperes', max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('power_factor', models.DecimalField(blank=True, decimal_places=3, help_text='Power factor (between 0 and 1)', max_digits=4, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['meter_id', 'timestamp'], name='measurement_meter_i_c69739_idx'), models.Index(fields=['timestamp'], name='measurement_timesta_f98167_idx')],
                'unique_together': {('meter_id', 'timestamp')},
            },
        ),
    ]
