# Generated by Django 4.2.7 on 2025-11-01 19:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurements', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='measurement',
            name='current',
        ),
        migrations.RemoveField(
            model_name='measurement',
            name='power_factor',
        ),
        migrations.RemoveField(
            model_name='measurement',
            name='voltage',
        ),
        migrations.AddField(
            model_name='measurement',
            name='average_power_kw',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Average power during period (kW)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='measurement',
            name='cost_per_kwh',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Cost per kilowatt-hour ($/kWh)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='measurement',
            name='duration_minutes',
            field=models.IntegerField(blank=True, help_text='Duration of measurement period in minutes', null=True),
        ),
        migrations.AddField(
            model_name='measurement',
            name='end_timestamp',
            field=models.DateTimeField(blank=True, help_text='End time of measurement period', null=True),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='consumption_kwh',
            field=models.DecimalField(decimal_places=3, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='meter_id',
            field=models.CharField(default='APARTMENT_METER', max_length=100),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='timestamp',
            field=models.DateTimeField(help_text='Start time of measurement'),
        ),
    ]
